name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install .NET 10.0.x
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - name: Build (strict)
        id: strict
        continue-on-error: true
        run: dotnet build -c Debug -warnaserror -p:EnforceCodeStyleInBuild=true

      - name: Build (fallback)
        if: steps.strict.outcome == 'failure'
        run: |
          dotnet build -c Debug -p:EnforceCodeStyleInBuild=true

      - name: Unit Tests
        run: dotnet test --no-build --no-restore

      - name: Crash
        if: steps.strict.outcome == 'failure'
        run: |
          echo ::error title=Build has warnings!::
          exit 1